Adapt sensitivity tutorial after sensi API refactoring
powsybl/powsybl-tutorials pull request #33
Opened 2020-09-21 12:08 UTC by TheMaskedTurtle

Signed-off-by: Joris Mancini <joris.mancini@rte-france.com>

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Adapt tutorial code to sensi API refactoring

2020-10-02 08:42 UTC, mathbagu requested changes

2020-10-02 08:42 UTC, mathbagu commented on sensitivity/complete/src/main/java/powsybl/tutorials/sensitivity/SensitivityTutorialComplete.java
> +        SensitivityAnalysisResults sensiResults = SensitivityAnalysis.find().run(network, factorsProvider);
Remove the extra call to the find() method

2020-10-02 08:42 UTC, mathbagu commented on sensitivity/complete/src/main/java/powsybl/tutorials/sensitivity/SensitivityTutorialComplete.java
> +        SensitivityAnalysisResults systematicSensiResults = SensitivityAnalysis.find().run(network,
Remove the call to the find() method

2020-10-05 06:53 UTC, murgeyseb approved these changes

2020-10-22 12:22 UTC, merged

2020-10-22 12:23 UTC, annetill commented
@TheMaskedTurtle Thanks a lot for your contribution !