[WIP] Upgrade loadflow tutorial (v4.0.1)
powsybl/powsybl-tutorials pull request #42
Opened 2021-02-24 11:47 UTC by armic-artelys

Warning: the changes in this PR do not run correctly (WIP)!
Everything seems to work fine while running the code in IntelliJ, but it will crash when running it with the maven `exec:java` goal.

The following error gets thrown:
`Cannot importer network of type: com.powsybl.iidm.network.impl.NetworkImpl`

-----

…flow for computations

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2021-02-24 16:34 UTC, floriand-e2r commented
Using maven exec:exec goal instead of exec:java solves it.

2021-02-25 08:01 UTC, annetill requested changes
We have first to fix the bug you have found. Thanks for introducing the logger, but you have left the System.out.printl ìn the web site: coherence is important. But what I don't understand is: why have you deleted all the comments? It is a tutorial, not an industrial code and the aim is to explain, maybe more than not enough.

2021-02-25 08:01 UTC, annetill commented on loadflow/complete/src/main/java/powsybl/tutorials/loadflow/LoadflowTutorialComplete.java
> +    private static final Logger LOG = LoggerFactory.getLogger(LoadflowTutorialComplete.class);
We use `LOGGER` for the whole powsybl organisation, it is better to keep the coherence and it makes the code more easy to read.

2021-02-25 08:01 UTC, annetill commented on loadflow/complete/src/main/java/powsybl/tutorials/loadflow/LoadflowTutorialComplete.java
> +            LOG.info("Angle difference   : " + (angle - oldAngle));
No space in english.

2021-02-25 09:47 UTC, armic-artelys commented
Has to close the PR because of problematic commit (too many files were committed altogether)

2021-02-25 09:47 UTC, closed without merging