Update tutorials with last versions
powsybl/powsybl-tutorials pull request #53
Opened 2022-03-31 14:21 UTC by annetill

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the following:*
- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration guide has been updated in the github wiki *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-03-31 14:35 UTC, annetill commented on cgmes/pom.xml
> +            <!-- Use powsybl-config-classic for your local config -->
I don't know if it is a good practice to put `powsybl-config-test`, but it works. I assume that it loads default parameters.

2022-04-04 08:19 UTC, flo-dup requested changes
Thanks for updating and cleaning up those tutorials! At last we get rid of the confusing initial / complete duplication.

2022-04-04 08:19 UTC, flo-dup commented on emf/pom.xml
> +                            <value>${project.basedir}/src/main/resources</value>
why didn't you keep the previous one?

2022-04-04 08:19 UTC, flo-dup commented on cgmes/pom.xml
> +            <!-- Use powsybl-config-classic for your local config -->
well, I find config-test quite strange when it comes to adding config files, but otherwise I find it good to use it in tutorials as you might otherwise get your local config without noticing it (well, if powsybl.config.dirs key is not specified)

2022-04-04 08:19 UTC, flo-dup commented on cgmes/src/main/java/powsybl/tutorials/cgmes/CgmesMergeTutorial.java
> +                        + generator.getTerminal().getP() + " MW " + generator.getMaxP());
we should maybe add something to tell that the printed value is maxP

2022-04-04 08:19 UTC, flo-dup commented on emf/pom.xml
> +    <!-- These properties are only needed to run the tutorial easily -->
good point to explain that, but "easily"... it depends who's using it, as it is easy in the sense that you don't need an IDE to launch it. Should we add this comment in all the other poms?

2022-04-04 08:19 UTC, flo-dup commented on sensitivity/src/main/java/powsybl/tutorials/sensitivity/SensitivityTutorial.java
> +        monitoredLines.forEach(l -> {
you could also use `List<SensitivityFactor> factors = monitoredLines.stream().map(l -> sensitivityFactor).collect(Collectors.toList());`

2022-04-04 08:19 UTC, flo-dup commented on topology/pom.xml
>              <artifactId>log4j-over-slf4j</artifactId>
I think we don't need this

2022-04-21 12:46 UTC, annetill reviewed
Approved, thanks a lot !

2022-04-21 12:46 UTC, merged